### ISSUE TITLE
NullPointerException caused by null values inside generator.fragment.Type

### ISSUE THREAD

**Issue by saiema** [kaiyuanw/ARepair#5]
Method `generator.util.Util#getLCAType(String, String, Map<String, String>)` will return `null` in some cases where a _"lowest common ancestor type for both leftType and rightType"_ does exist, specifically between `univ` and any other type.

To replicate the bug:
1. Download all files inside ARepair root folder.
2. Rename `replicateBug.txt` to `replicateBug.sh`.
3. Execute `chmod +x replicateBug.sh`.
4. Rename both `tests.txt` and `toFix.txt` replacing `txt` with `als`.
5. Execute `./replicateBug.sh`.

ARepair should be able to find a repair, instead it crashes with a `NullPointerException`

```bash
Exception in thread "main" java.lang.NullPointerException
	at synthesizer.util.Util.isSimilarType(Util.java:59)
	at synthesizer.Synthesizer.lambda$getExpressionsFromType$6(Synthesizer.java:209)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at synthesizer.Synthesizer.lambda$getExpressionsFromType$7(Synthesizer.java:208)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at synthesizer.Synthesizer.getExpressionsFromType(Synthesizer.java:207)
	at synthesizer.Synthesizer.lambda$synthesize$12(Synthesizer.java:291)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at synthesizer.Synthesizer.synthesize(Synthesizer.java:283)
	at patcher.Patcher.patch(Patcher.java:142)
	at patcher.Patcher.main(Patcher.java:341)
```

[replicateBug.txt](https://github.com/kaiyuanw/ARepair/files/9561285/replicateBug.txt)
[tests.txt](https://github.com/kaiyuanw/ARepair/files/9561288/tests.txt)
[toFix.txt](https://github.com/kaiyuanw/ARepair/files/9561289/toFix.txt)

**Comment by saiema** [comment]
I'll make a pull request soon with a proposed fix
